# Generated by Django 4.1.3 on 2022-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eliminatorias_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eliminatorias',
            options={'verbose_name': 'Eliminatórias', 'verbose_name_plural': 'Eliminatórias'},
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroA',
            field=models.CharField(choices=[('Quatar', 'Qatar'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal')], default='Quatar', max_length=20),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoB',
            field=models.CharField(choices=[('Estados Unidos', 'Estados Unidos'), ('País de Gales', 'País de Gales'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irâ')], default='País de Gales', max_length=20),
        ),
    ]
