# Generated by Django 4.1.3 on 2022-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_eliminatorias_primeiroa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroA',
            field=models.CharField(blank=True, default='Primeiro A', max_length=200, null=True, verbose_name='Primeiro A'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroB',
            field=models.CharField(blank=True, default='Primeiro B', max_length=200, null=True, verbose_name='Primeiro B'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroC',
            field=models.CharField(blank=True, default='Primeiro C', max_length=200, null=True, verbose_name='Primeiro C'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroD',
            field=models.CharField(blank=True, default='Primeiro D', max_length=200, null=True, verbose_name='Primeiro D'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroE',
            field=models.CharField(blank=True, default='Primeiro E', max_length=200, null=True, verbose_name='Primeiro E'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroF',
            field=models.CharField(blank=True, default='Primeiro F', max_length=200, null=True, verbose_name='Primeiro F'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroG',
            field=models.CharField(blank=True, default='Primeiro G', max_length=200, null=True, verbose_name='Primeiro G'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='primeiroH',
            field=models.CharField(blank=True, default='Primeiro H', max_length=200, null=True, verbose_name='Primeiro H'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoA',
            field=models.CharField(blank=True, default='Segundo A', max_length=200, null=True, verbose_name='Segundo A'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoB',
            field=models.CharField(blank=True, default='Segundo B', max_length=200, null=True, verbose_name='Segundo B'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoC',
            field=models.CharField(blank=True, default='Segundo C', max_length=200, null=True, verbose_name='Segundo C'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoD',
            field=models.CharField(blank=True, default='Segundo D', max_length=200, null=True, verbose_name='Segundo D'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoE',
            field=models.CharField(blank=True, default='Segundo E', max_length=200, null=True, verbose_name='Segundo E'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoF',
            field=models.CharField(blank=True, default='Segundo F', max_length=200, null=True, verbose_name='Segundo F'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoG',
            field=models.CharField(blank=True, default='Segundo G', max_length=200, null=True, verbose_name='Segundo G'),
        ),
        migrations.AlterField(
            model_name='eliminatorias',
            name='segundoH',
            field=models.CharField(blank=True, default='Segundo H', max_length=200, null=True, verbose_name='Segundo H'),
        ),
    ]
