# Generated by Django 4.1.3 on 2022-11-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_eliminatorias_primeiroa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoa',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoa',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupob',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupob',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoc',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoc',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupod',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupod',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoe',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoe',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupof',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupof',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupog',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupog',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoh',
            name='primeiroColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
        migrations.AddField(
            model_name='grupoh',
            name='segundoColocado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primeiro Lugar'),
        ),
    ]
