# Generated by Django 4.1.3 on 2022-11-14 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_grupoa_primeirocolocado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('melhorJogador', models.CharField(blank=True, max_length=200, null=True, verbose_name='Melhor Jogador')),
                ('artilheiro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Melhor Jogador')),
                ('melhorJogadorJovem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Melhor Jogador Jovem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Premiação Individual',
                'verbose_name_plural': 'Premiação Individual',
            },
        ),
    ]
