# Generated by Django 4.1.3 on 2022-11-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_premioindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='premioindividual',
            name='artilheiroGols',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Gols Artilheiro'),
        ),
    ]
