# Generated by Django 4.1.3 on 2022-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_premioindividual_artilheirogols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premioindividual',
            name='artilheiro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Melhor Jogador'),
        ),
        migrations.AlterField(
            model_name='premioindividual',
            name='melhorJogador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Melhor Jogador'),
        ),
        migrations.AlterField(
            model_name='premioindividual',
            name='melhorJogadorJovem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Melhor Jogador Jovem'),
        ),
    ]
