# Generated by Django 4.1.3 on 2022-11-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_premioindividual_artilheiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premioindividual',
            name='artilheiro',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Melhor Jogador'),
        ),
        migrations.AlterField(
            model_name='premioindividual',
            name='artilheiroGols',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Gols Artilheiro'),
        ),
        migrations.AlterField(
            model_name='premioindividual',
            name='melhorJogador',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Melhor Jogador'),
        ),
        migrations.AlterField(
            model_name='premioindividual',
            name='melhorJogadorJovem',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Melhor Jogador Jovem'),
        ),
    ]
