# Generated by Django 4.1.3 on 2022-11-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_pontuacaousuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacaousuarios',
            name='artilheiroGols',
        ),
        migrations.AddField(
            model_name='pontuacaousuarios',
            name='pontos',
            field=models.SmallIntegerField(default=0, verbose_name='Pontos'),
        ),
    ]
